In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
customer = pd.read_csv("customers.csv")
employee = pd.read_csv("employees.csv")
product = pd.read_csv("products.csv")
order = pd.read_csv("orders.csv")
review = pd.read_csv("reviews.csv")

In [3]:
print(customer.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 512 entries, 0 to 511
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  512 non-null    object
 1   name         485 non-null    object
 2   age          512 non-null    int64
 3   gender       512 non-null    object
 4   city         492 non-null    object
 5   signup_date  512 non-null    object
dtypes: int64(1), object(5)
memory usage: 24.1+ KB
None

In [4]:
customer.isnull().sum()

customer_id     0
name           27
age             0
gender          0
city           20
signup_date     0
dtype: int64

In [5]:
customer.count()

customer_id    512
name           485
age            512
gender         512
city           492
signup_date    512
dtype: int64

In [6]:
customer=customer.dropna()

In [7]:
customer.isnull().sum()

customer_id    0
name           0
age            0
gender         0
city           0
signup_date    0
dtype: int64

In [8]:
customer['gender'].unique()

array(['FEMALE', 'MALE', 'Male', 'male', 'Female', 'female'], dtype=object)

In [9]:
customer['gender'].unique()

array(['FEMALE', 'MALE', 'Male', 'male', 'Female', 'female'], dtype=object)

In [10]:
customer.head()

  customer_id     name  age  gender        city signup_date
0       C0001   AYESHA   19  FEMALE  rawalpindi  2023-04-03
1       C0002  hassan    24    MALE     Sialkot  2024-05-14
2       C0003    Sara    19    Male  Rawalpindi  2023-04-22
3       C0004   Shayan   56    male       swabi  2023-02-12
4       C0005   Muneeb   44    Male      Quetta  2025-04-21

In [11]:
customer['gender']=customer['gender'].str.capitalize()
customer['name'] = customer['name'].str.strip().str.capitalize()
customer['city'] = customer['city'].str.strip().str.capitalize()

In [12]:
customer.isnull().sum()

customer_id    0
name           0
age            0
gender         0
city           0
signup_date    0
dtype: int64

In [13]:
customer=customer.dropna()

In [14]:
customer.isnull().sum()

customer_id    0
name           0
age            0
gender         0
city           0
signup_date    0
dtype: int64

In [15]:
customer.head()

  customer_id    name  age  gender        city signup_date
0       C0001  Ayesha   19  Female  Rawalpindi  2023-04-03
1       C0002  Hassan   24    Male     Sialkot  2024-05-14
2       C0003    Sara   19    Male  Rawalpindi  2023-04-22
3       C0004  Shayan   56    Male       Swabi  2023-02-12
4       C0005  Muneeb   44    Male      Quetta  2025-04-21

In [16]:
print((customer['signup_date'].dtype))

object

In [17]:
customer['signup_date'] = pd.to_datetime(
    customer['signup_date'],
    format='mixed',
    errors='coerce'
)

In [18]:
customer.head()

  customer_id    name  age  gender        city signup_date
0       C0001  Ayesha   19  Female  Rawalpindi  2023-04-03
1       C0002  Hassan   24    Male     Sialkot  2024-05-14
2       C0003    Sara   19    Male  Rawalpindi  2023-04-22
3       C0004  Shayan   56    Male       Swabi  2023-02-12
4       C0005  Muneeb   44    Male      Quetta  2025-04-21

In [19]:
employee['employee_name'] = employee['employee_name'].str.replace(r'\s+\d+$', '', regex=True)

In [20]:
employee['department']=employee['department'].str.capitalize()

In [21]:
employee.head()

,employee_id,employee_name,department,salary,hire_date,city,performance_score
0,E001,Hassan Raza,Marketing,251372.0,2020-06-24,Peshawar,3.32
1,E002,Ali Khan,Customer support,46162.0,2019-01-10,NaN,2.81
2,E003,Sana Iqbal,Operations,9999999.0,2020-10-07,Peshawar,2.44
3,E004,Ali Khan,Hr,89522.0,2024-12-08,NaN,1.36
4,E005,Sara Ahmed,It,57955.0,2020-05-28,LAHORE,NaN

In [22]:
employee['department'].unique()

array(['Marketing', 'Customer support', 'Operations', 'Hr', 'It',
       'Finance', 'Sales', nan], dtype=object)

In [23]:
employee['department']=employee['department'].replace({
    'Hr':'HR',
    'It':'IT'
})

In [24]:
employee['department'].unique()

array(['Marketing', 'Customer support', 'Operations', 'HR', 'IT',
       'Finance', 'Sales', nan], dtype=object)

In [25]:
print(employee['hire_date'].dtype)

object

In [26]:
employee['hire_date'] = pd.to_datetime(
    employee['hire_date'],
    format='mixed',
    errors='coerce'
)

In [27]:
employee.isnull().sum()

employee_id          0
employee_name        3
department           3
salary               3
hire_date            0
city                 3
performance_score    3
dtype: int64

In [28]:
employee=employee.dropna()

In [29]:
product.head()

,product_id,product_name,category,subcategory,price,cost,stock,rating,supplier
0,P0001,Men Max 1,CLOTHING,MEN,135747.02,111221.97,233,3.4,stylehub
1,P0002,Mobile Elite 2,ELECTRONICS,mobile,74822.95,60578.82,32,NaN,global traders
2,P0003,Technology Plus 3,Books,TECHNOLOGY,48973.12,43543.66,-1,4.3,homemart
3,P0004,laptop plus 4,ELECTRONICS,Laptop,50657.81,25548.53,212,1.7,BEAUTYPLUS
4,P0005,Cricket Pro 5,sports,CRICKET,66079.85,57261.76,68,1.4,GLOBAL TRADERS

In [30]:
product['product_name'] = product['product_name'].str.replace(r'\s+\d+$', '', regex=True)
product['product_name']=product['product_name'].str.capitalize()
product['product_name']=product['product_name'].str.strip().str.capitalize()
product['category']=product['category'].str.strip().str.capitalize()
product['subcategory']=product['subcategory'].str.strip().str.capitalize()
product['supplier']=product['supplier'].str.strip().str.capitalize()

In [31]:
product.head()

,product_id,product_name,category,subcategory,price,cost,stock,rating,supplier
0,P0001,Men max 1,Clothing,Men,135747.02,111221.97,233,3.4,Stylehub
1,P0002,Mobile elite 2,Electronics,Mobile,74822.95,60578.82,32,NaN,Global traders
2,P0003,Technology plus,Books,Technology,48973.12,43543.66,-1,4.3,Homemart
3,P0004,Laptop plus,Electronics,Laptop,50657.81,25548.53,212,1.7,Beautyplus
4,P0005,Cricket pro,Sports,Cricket,66079.85,57261.76,68,1.4,Global traders

In [32]:
product.isnull().sum()

product_id      0
product_name    0
category        0
subcategory     0
price           5
cost            5
stock           0
rating          5
supplier        6
dtype: int64

In [33]:
product=product.dropna()

In [34]:
order.head()

,order_id,customer_id,product_id,order_date,quantity,discount,payment_method,order_status
0,O00001,C0058,P0003,2024-01-21,3,0.05,EasyPaisa,Cancelled
1,O00002,C0333,P0031,2025-06-11,3,0.30,Bank Transfer,CANCELLED
2,O00003,C0045,P0039,2025-08-07,1,0.15,Cash,Completed
3,O00004,C0086,P0020,2025-06-30,5,0.15,CASH,Pending
4,O00005,C0300,P0032,2024-02-17,1,0.30,EasyPaisa,Completed

In [35]:
order['order_status'].unique()

array(['Cancelled', 'CANCELLED', 'Completed', 'Pending', 'PENDING',
       'Returned', 'cancelled', 'returned', 'COMPLETED', 'completed',
       'pending', 'RETURNED'], dtype=object)

In [36]:
order.isnull().sum()

order_id           0
customer_id       20
product_id        20
order_date        20
quantity           0
discount           0
payment_method    20
order_status       0
dtype: int64

In [37]:
order=order.dropna()

In [38]:
order['order_date'] = pd.to_datetime(
    order['order_date'],
    format='mixed',
    errors='coerce'
)

In [39]:
order['payment_method']=order['payment_method'].str.strip().str.capitalize()
order['order_status']=order['order_status'].str.strip().str.capitalize()

In [40]:
order.columns

Index(['order_id', 'customer_id', 'product_id', 'order_date', 'quantity',
       'discount', 'payment_method', 'order_status'],
      dtype='object')

In [41]:
review.head()

  review_id customer_id product_id  rating            review_text review_date
0    R00001       C0373      P0085       5      VERY GOOD QUALITY  2023-05-15
1    R00002       C0196      P0058       5    terrible experience  2025-12-04
2    R00003       C0142      P0003       5        Poor packaging   2023-11-23
3    R00004       C0094      P0038       5   Terrible experience   10/04/2025
4    R00005       C0312      P0083       4    terrible experience  2023-09-01

In [42]:
review.isnull().sum()

review_id       0
customer_id    15
product_id     15
rating          0
review_text    15
review_date    15
dtype: int64

In [43]:
review=review.dropna()

In [44]:
review['review_date'] = pd.to_datetime(
    review['review_date'],
    format='mixed',
    errors='coerce'
)

In [45]:
review['review_text']=review['review_text'].str.strip().str.capitalize()

In [46]:
print('Customer Dataset')
print(customer.head())
print('*************************')
print('employee Dataset')
print(employee.head())
print('*************************')
print('Product Dataset')
print(product.head())
print('*************************')
print('Order Dataset')
print(order.head())
print('*************************')
print('Review Dataset')
print(review.head())
print()

Customer Dataset
  customer_id    name  age  gender        city signup_date
0       C0001  Ayesha   19  Female  Rawalpindi  2023-04-03
1       C0002  Hassan   24    Male     Sialkot  2024-05-14
2       C0003    Sara   19    Male  Rawalpindi  2023-04-22
3       C0004  Shayan   56    Male       Swabi  2023-02-12
4       C0005  Muneeb   44    Male      Quetta  2025-04-21
*************************
employee Dataset
  employee_id employee_name        department     salary  hire_date  \
0        E001   Hassan Raza         Marketing   251372.0 2020-06-24
2        E003    Sana Iqbal        Operations  9999999.0 2020-10-07
5        E006    Fatima Ali  Customer support        0.0 2018-10-16
6        E007    Sara Ahmed           Finance   245730.0 2024-03-28
7        E008    Bilal Shah  Customer support  9999999.0 2025-07-25

        city  performance_score
0   Peshawar               3.32
2   Peshawar               2.44
5     Quetta               1.02
6   Peshawar               4.42
7  islamabad               4.18
*************************
Product Dataset
  product_id     product_name     category subcategory      price       cost  \
0      P0001        Men max 1     Clothing         Men  135747.02  111221.97
2      P0003  Technology plus        Books  Technology   48973.12   43543.66
3      P0004      Laptop plus  Electronics      Laptop   50657.81   25548.53
4      P0005      Cricket pro       Sports     Cricket   66079.85   57261.76
5      P0006          Men pro     Clothing         Men  132004.23   64196.98

   stock  rating        supplier
0    233     3.4        Stylehub
2     -1     4.3        Homemart
3    212     1.7      Beautyplus
4     68     1.4  Global traders
5     91    10.0       Sportzone
*************************
Order Dataset
  order_id customer_id product_id order_date  quantity  discount  \
0   O00001       C0058      P0003 2024-01-21         3      0.05
1   O00002       C0333      P0031 2025-06-11         3      0.30
2   O00003       C0045      P0039 2025-08-07         1      0.15
3   O00004       C0086      P0020 2025-06-30         5      0.15
4   O00005       C0300      P0032 2024-02-17         1      0.30

  payment_method order_status
0      Easypaisa    Cancelled
1  Bank transfer    Cancelled
2           Cash    Completed
3           Cash      Pending
4      Easypaisa    Completed
*************************
Review Dataset
  review_id customer_id product_id  rating          review_text review_date
0    R00001       C0373      P0085       5    Very good quality  2023-05-15
1    R00002       C0196      P0058       5  Terrible experience  2025-12-04
2    R00003       C0142      P0003       5       Poor packaging  2023-11-23
3    R00004       C0094      P0038       5  Terrible experience  2025-10-04
4    R00005       C0312      P0083       4  Terrible experience  2023-09-01

In [47]:
print('Hello-World')

Hello-World

In [50]:
order_count=order[order['order_status']=='Completed']
print(len(order_count))

1089

In [49]:
order.columns

Index(['order_id', 'customer_id', 'product_id', 'order_date', 'quantity',
       'discount', 'payment_method', 'order_status'],
      dtype='object')

In [52]:
df_orders = order.merge(
    product[["product_id", "price"]],
    on="product_id",
    how="left"
)

df_orders["spending"] = df_orders["price"] * df_orders["quantity"]

In [58]:
df_orders["price"] = df_orders["price"].abs()
df_orders["quantity"] = df_orders["quantity"].abs()
df_orders["spending"] = df_orders["spending"].abs()

In [59]:
df_orders.head()

,order_id,customer_id,product_id,order_date,quantity,discount,payment_method,order_status,price,spending
0,O00001,C0058,P0003,2024-01-21,3,0.05,Easypaisa,Cancelled,48973.12,146919.36
1,O00002,C0333,P0031,2025-06-11,3,0.30,Bank transfer,Cancelled,48409.34,145228.02
2,O00003,C0045,P0039,2025-08-07,1,0.15,Cash,Completed,NaN,NaN
3,O00004,C0086,P0020,2025-06-30,5,0.15,Cash,Pending,109637.65,548188.25
4,O00005,C0300,P0032,2024-02-17,1,0.30,Easypaisa,Completed,100.00,100.00