In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [28]:
customer = pd.read_csv("customers.csv")
employee = pd.read_csv("employees.csv")
product = pd.read_csv("products.csv")
order = pd.read_csv("orders.csv")
review = pd.read_csv("reviews.csv")

In [5]:
print(customer.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 512 entries, 0 to 511
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  512 non-null    object
 1   name         485 non-null    object
 2   age          512 non-null    int64
 3   gender       512 non-null    object
 4   city         492 non-null    object
 5   signup_date  512 non-null    object
dtypes: int64(1), object(5)
memory usage: 24.1+ KB
None

In [7]:
customer.isnull().sum()

customer_id     0
name           27
age             0
gender          0
city           20
signup_date     0
dtype: int64

In [10]:
customer.count()

customer_id    512
name           485
age            512
gender         512
city           492
signup_date    512
dtype: int64

In [12]:
customer=customer.dropna()

In [14]:
customer.isnull().sum()

customer_id    0
name           0
age            0
gender         0
city           0
signup_date    0
dtype: int64

In [16]:
customer['gender'].unique()

array(['FEMALE', 'MALE', 'Male', 'male', 'Female', 'female'], dtype=object)

In [18]:
customer['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [29]:
customer.head()

  customer_id     name  age  gender        city signup_date
0       C0001   AYESHA   19  FEMALE  rawalpindi  2023-04-03
1       C0002  hassan    24    MALE     Sialkot  2024-05-14
2       C0003    Sara    19    Male  Rawalpindi  2023-04-22
3       C0004   Shayan   56    male       swabi  2023-02-12
4       C0005   Muneeb   44    Male      Quetta  2025-04-21

In [41]:
customer['gender']=customer['gender'].str.capitalize()
customer['name'] = customer['name'].str.strip().str.capitalize()

In [31]:
customer.isnull().sum()

customer_id     0
name           27
age             0
gender          0
city           20
signup_date     0
dtype: int64

In [34]:
customer=customer.dropna()

In [35]:
customer.isnull().sum()

customer_id    0
name           0
age            0
gender         0
city           0
signup_date    0
dtype: int64

In [42]:
customer.head()

  customer_id    name  age  gender        city signup_date
0       C0001  Ayesha   19  Female  rawalpindi  2023-04-03
1       C0002  Hassan   24    Male     Sialkot  2024-05-14
2       C0003    Sara   19    Male  Rawalpindi  2023-04-22
3       C0004  Shayan   56    Male       swabi  2023-02-12
4       C0005  Muneeb   44    Male      Quetta  2025-04-21

In [45]:
print((customer['signup_date'].dtype))

object

In [46]:
customer['signup_date'] = pd.to_datetime(customer['signup_date'])

ValueError: time data "2022/09/13" doesn't match format "%Y-%m-%d", at position 7. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.