## Introduction to Pandas

In [16]:
import pandas as pd

In [17]:
info={
    'Name':['Shayan','Noman','Hamdan','Sanan','Zaid'],
    'Age':[23,15,15,26,20]
}
df=pd.DataFrame(info)
df

     Name  Age
0  Shayan   23
1   Noman   15
2  Hamdan   15
3   Sanan   26
4    Zaid   20

In [18]:
s=pd.Series([11,22,33,44,55])
s

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [19]:
SS=pd.Series([11,22,33,44,55],['Shayan','Noman','Hamdan','Sanan','Zaid'])
SS

Shayan    11
Noman     22
Hamdan    33
Sanan     44
Zaid      55
dtype: int64

In [20]:
s1=pd.Series([11,22,33,44,55])
s2=pd.Series([1,2,3,4,5])
print(s1+s2)

0    12
1    24
2    36
3    48
4    60
dtype: int64

In [21]:
s3=s1.drop(2)
s3

0    11
1    22
3    44
4    55
dtype: int64

In [22]:
len(s3)

4

In [23]:
len(s1)

5

In [31]:
df=pd.DataFrame([['Shayan',23],['Sanan',36],['Noman',15],['Hamdan',15],['Zaid',21]],columns=['Name','Age'])
df

     Name  Age
0  Shayan   23
1   Sanan   36
2   Noman   15
3  Hamdan   15
4    Zaid   21

In [28]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [32]:
df.columns

Index(['Name', 'Age'], dtype='object')

In [33]:
data=pd.read_csv('employee_data.csv')
data

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000